title: <p align="center"> Manepalli Jagadeesh</p>
logo: /assets/img/my_photo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/manepalli-jagadeesh/">LinkedIn</a> |
  <a href="https://github.com/cdacjitthu">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with Robert Bosch Engineering & Business Solutions Pvt. Ltd.
  Working in Globallogic India Pvt. Ltd and client location is Adobe.
  <br>
  </p>



theme: jekyll-theme-minimal
